### ISSUE TITLE
Min/max labels positioning

### ISSUE THREAD

**Issue by nikshulipa** [rzajac/angularjs-slider#90]
Is there any option where slider should render labels (e.g. on the top is default for now, but what about bottom position?) I know we can do it in styles but it will be nice have this out-of-the-box since it works via "style" attr...

**Comment by ValentinH** [comment]
The easiest way is to override the CSS rule. The vertical position is not defined via a "style" attr but directly in the css file. So you just need to set something like:
```css
.rz-bubble {
  top: 6px;
}
```

**Comment by nikshulipa** [comment]
Ok, got it. Thanks!

**Comment by ValentinH** [comment]
Actually, you need that:
```css
rzslider span.rz-bubble {
  top: 20px;
}
```
Example: http://jsfiddle.net/asqbmtLs/
